version: '3.8'
services:
    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto:2.0
        restart: unless-stopped
        volumes:
            - '.container-data/mosquitto:/mosquitto'
        ports:
            - '1883:1883'
            - '9001:9001'
        command: 'mosquitto -c /mosquitto-no-auth.conf'

    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        volumes:
            - .container-data/zigbee2mqtt:/app/data
            - /run/udev:/run/udev:ro
        ports:
            - 8080:8080
        environment:
            - TZ=Europe/Berlin
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0